### ISSUE TITLE
Is gen_distribution_ops.py missing?

### ISSUE THREAD

**Issue by GoingMyWay** [deepmind/trfl#11]
In https://github.com/deepmind/trfl/blob/master/trfl/distribution_ops.py#L30, I found

    from trfl import gen_distribution_ops

But it seems that there is no such `gen_distribution_ops.py` in source code. Is gen_distribution_ops.py missing?

**Comment by mtthss** [comment]
`gen_distribution_ops` are created in `trfl/trfl/BUILD` by wrapping `cc/distribution_ops.cc`

**Comment by mtthss** [comment]
`gen_distribution_ops` are created in `trfl/trfl/BUILD` by wrapping `cc/distribution_ops.cc` using `gen_op_wrapper_py`
