### ISSUE TITLE
import trfl not working

### ISSUE THREAD

**Issue by Deepak08wc** [deepmind/trfl#13]
I am using Spyder (Python 3.6) in ubuntu 18.04
import tensorflow

import trfl

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

Traceback (most recent call last):

  File "<ipython-input-2-dd69192d7d7c>", line 1, in <module>
    import trfl

  File "/home/dd/.local/lib/python3.6/site-packages/trfl/__init__.py", line 31, in <module>
    from trfl.dist_value_ops import categorical_dist_double_qlearning

  File "/home/dd/.local/lib/python3.6/site-packages/trfl/dist_value_ops.py", line 33, in <module>
    from trfl import distribution_ops

  File "/home/dd/.local/lib/python3.6/site-packages/trfl/distribution_ops.py", line 30, in <module>
    from trfl import gen_distribution_ops

  File "/home/dd/.local/lib/python3.6/site-packages/trfl/gen_distribution_ops.py", line 2, in <module>
    _op_lib = tf.load_op_library(tf.resource_loader.get_path_to_datafile("_gen_distribution_ops.so"))

  File "/home/dd/.local/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)

NotFoundError: /home/dd/.local/lib/python3.6/site-packages/trfl/_gen_distribution_ops.so: undefined symbol: _ZN10tensorflow14kernel_factory17OpKernelRegistrar12InitInternalEPKNS_9KernelDefEN4absl11string_viewEPFPNS_8OpKernelEPNS_20OpKernelConstructionEE

**Comment by mtthss** [comment]
how did you install trfl?

**Comment by janyChan** [comment]
I have the same issue

**Comment by janyChan** [comment]
> how did you install trfl?

sudo pip3 install trfl

**Comment by diegolascasas** [comment]
Hi @janyChan and @Deepak08wc.
This is an internal issue of ours. `trfl` was compiled for Tensorflow 1.12, so the precompiled code we ship to PyPI is for this version. We're working into this, but meanwhile you can get it working by either using Tensorflow 1.12. (`pip uninstall tensorflow && pip install tensorflow==1.12`) or compiling `trfl` locally.

**Comment by janyChan** [comment]
I install them now. I think the tensorflow-probability could use 0.5.0 version.

**Comment by Deepak08wc** [comment]
Hi @mtthss ,
I used following command to install trfl:
pip3 install --user --upgrade trfl

**Comment by Deepak08wc** [comment]
Thanks @diegolascasas ,
I'll try your suggestion and respond you back.

**Comment by mtthss** [comment]
We now have pre-built binaries for both MacOS and Ubuntu. You can install them with `pip install trfl`.

- Ubuntu: make sure you have TensorFlow 1.12.0 and TensorFlow Probability 0.5
- MacOS: make sure you have TensorFlow 1.13.1 and TensorFlow Probability 0.6

If you are building locally, whether you build with MacOS or Ubuntu, make sure you use one of the combinations above. Either TF-1.12 with TFP-0.5 or TF-1.13.1 with TFP-0.6.

The error you observe is due to the fact that you currently are mixing TFP-0.6 with TF-1.12 which are not compatible.

**Comment by Deepak08wc** [comment]
Thank You @mtthss 
It worked :)
