### ISSUE TITLE
Removing tf.contrib 

### ISSUE THREAD

**Issue by LuisSaybe** [deepmind/trfl#15]
Would you be open to accepting a PR to remove code using tf.contrib as it won't be available in TF 2 ?

**Comment by mtthss** [comment]
Hi, Thanks for the suggestion!

However, currently TRFL depends on `tf.contrib` only via `tf.contrib.nest`,
and we are waiting for `nest` to be exposed either as a standalone library or as part of core TF.

**Comment by LuisSaybe** [comment]
alrighty, sounds good thanks
