### ISSUE TITLE
Unable to install trfl on Windows 10 via Anaconda Prompt

### ISSUE THREAD

**Issue by realbitsurfer** [deepmind/trfl#19]
Neither of the two installing options seem to work for me.

The command `pip install trfl` throws the following error:

`Collecting trfl
  ERROR: Could not find a version that satisfies the requirement trfl (from versions: none)
ERROR: No matching distribution found for trfl`

And the command `pip install git+git://github.com/deepmind/trfl.git` throws this error:

...
 Building wheels for collected packages: trfl
  Building wheel for trfl (setup.py) ... error
  ERROR: Complete output from command 'c:\users\luis\anaconda3\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\Luis\\AppData\\Local\\Temp\\pip-req-build-5488atsp\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Luis\AppData\Local\Temp\pip-wheel-2xiqoy_g' --python-tag cp36:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  error: could not create 'build': file exists

  ----------------------------------------

  ERROR: Failed building wheel for trfl
  Running setup.py clean for trfl
Failed to build trfl
Installing collected packages: trfl
  Running setup.py install for trfl ... error
    ERROR: Complete output from command 'c:\users\luis\anaconda3\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\Luis\\AppData\\Local\\Temp\\pip-req-build-5488atsp\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Luis\AppData\Local\Temp\pip-record-82clib4d\install-record.txt' --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    error: could not create 'build': file exists
    ----------------------------------------
ERROR: Command "'c:\users\luis\anaconda3\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\Luis\\AppData\\Local\\Temp\\pip-req-build-5488atsp\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Luis\AppData\Local\Temp\pip-record-82clib4d\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Luis\AppData\Local\Temp\pip-req-build-5488atsp\`

**Comment by diegolascasas** [comment]
Hi @realbitsurfer, 

Since we have ship precompiled custom ops, we do not support Windows packages in `pip`.
You can still compile it yourself by running `confgure.sh`, then using `bazel` to build the `build_pip_package` rule and running it. This will give you a wheel file.
